apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: kernel-gossip
  annotations:
    kernel-gossip.io/monitor: "true"
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi