apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-gossip-operator
  namespace: kernel-gossip
  labels:
    app.kubernetes.io/name: kernel-gossip-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kernel-gossip
spec:
  replicas: 1  # Single replica for webhook handling
  selector:
    matchLabels:
      app.kubernetes.io/name: kernel-gossip-operator
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kernel-gossip-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: kernel-gossip
    spec:
      serviceAccountName: kernel-gossip-operator
      containers:
      - name: operator
        image: kernel-gossip-operator:latest  # TODO: Update with actual image
        imagePullPolicy: Always
        ports:
        - name: webhook
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: OPERATOR_PORT
          valueFrom:
            configMapKeyRef:
              name: kernel-gossip-operator-config
              key: OPERATOR_PORT
        - name: OPERATOR_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: kernel-gossip-operator-config
              key: OPERATOR_LOG_LEVEL
        - name: WEBHOOK_PATH
          valueFrom:
            configMapKeyRef:
              name: kernel-gossip-operator-config
              key: WEBHOOK_PATH
        - name: RUST_LOG
          value: kernel_gossip_operator=info,kube=info
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534  # nobody user
          capabilities:
            drop:
            - ALL