apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-demo
  namespace: kernel-gossip
  labels:
    app: cpu-stress
    demo: kernel-gossip
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args:
    - "--cpu"
    - "2"  # Use 2 CPU workers
    - "--timeout"
    - "300s"  # Run for 5 minutes
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"  # Request 0.2 CPU
      limits:
        memory: "256Mi"
        cpu: "500m"  # Limit to 0.5 CPU - will cause throttling!
    env:
    - name: DEMO_TYPE
      value: "cpu-throttle"
    - name: EXPECTED_RESULT
      value: "Should show high CPU throttling in kernel but low usage in metrics"