apiVersion: v1
kind: Service
metadata:
  name: nginx-target
  namespace: kernel-gossip
spec:
  selector:
    app: nginx-target
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-target
  namespace: kernel-gossip
  labels:
    app: nginx-target
  annotations:
    kernel-gossip.io/observe: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-target
  template:
    metadata:
      labels:
        app: nginx-target
      annotations:
        kernel-gossip.io/observe: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ddosify-load-test
  namespace: kernel-gossip
  annotations:
    kernel-gossip.io/observe: "true"
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        kernel-gossip.io/observe: "true"
    spec:
      restartPolicy: Never
      containers:
      - name: ddosify
        image: ddosify/ddosify:latest
        command: ["ddosify"]
        args:
        - "-t"
        - "http://nginx-target.kernel-gossip.svc.cluster.local"
        - "-n"
        - "10000"
        - "-c"
        - "100"
        - "-d"
        - "30"
        - "-m"
        - "GET"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"