apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  namespace: kernel-gossip
  labels:
    app: nginx
    demo: kernel-gossip
  annotations:
    demo.kernel.gossip.io/purpose: "Track syscalls during pod creation"
    demo.kernel.gossip.io/expected-syscalls: "~847"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5