apiVersion: v1
kind: Pod
metadata:
  name: nginx-birth-test
  namespace: kernel-gossip
  annotations:
    kernel-gossip.io/monitor: "true"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: 50m
      limits:
        cpu: 100m