apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpftrace-observer
  namespace: kernel-gossip
  labels:
    app: bpftrace-observer
spec:
  selector:
    matchLabels:
      app: bpftrace-observer
  template:
    metadata:
      labels:
        app: bpftrace-observer
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: syscall-counter
        image: gcr.io/scaleops-dev-rel/bpftrace-observer:v5
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_RESOURCE
            - SYS_PTRACE
            - NET_ADMIN
            - PERFMON
            - BPF
        env:
        - name: WEBHOOK_URL
          value: "http://kernel-gossip-operator.kernel-gossip.svc.cluster.local:8080/webhook/pixie"
        - name: EBPF_MODE
          value: "syscall"
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: tracefs
          mountPath: /sys/kernel/tracing
        - name: proc
          mountPath: /proc
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: boot
          mountPath: /boot
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1"
      - name: throttle-detector
        image: gcr.io/scaleops-dev-rel/bpftrace-observer:v5
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_RESOURCE
            - SYS_PTRACE
            - NET_ADMIN
            - PERFMON
            - BPF
        env:
        - name: WEBHOOK_URL
          value: "http://kernel-gossip-operator.kernel-gossip.svc.cluster.local:8080/webhook/pixie"
        - name: EBPF_MODE
          value: "throttle"
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: tracefs
          mountPath: /sys/kernel/tracing
        - name: proc
          mountPath: /proc
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: boot
          mountPath: /boot
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
          type: DirectoryOrCreate
      - name: tracefs
        hostPath:
          path: /sys/kernel/tracing
          type: DirectoryOrCreate
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: boot
        hostPath:
          path: /boot
          type: DirectoryOrCreate
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists