apiVersion: v1
kind: ServiceAccount
metadata:
  name: kernel-observer
  namespace: kernel-gossip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kernel-observer
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kernel-observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kernel-observer
subjects:
- kind: ServiceAccount
  name: kernel-observer
  namespace: kernel-gossip
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kernel-observer
  namespace: kernel-gossip
  labels:
    app.kubernetes.io/name: kernel-observer
    app.kubernetes.io/component: eBPF-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kernel-observer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kernel-observer
        app.kubernetes.io/component: eBPF-monitor
    spec:
      serviceAccountName: kernel-observer
      hostPID: true
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: kernel-observer
        image: gcr.io/scaleops-dev-rel/kernel-observer:latest
        imagePullPolicy: Always
        env:
        - name: WEBHOOK_URL
          value: "http://kernel-gossip-operator.kernel-gossip.svc.cluster.local:8080/webhook/pixie"
        - name: NAMESPACE
          value: "kernel-gossip"
        - name: RUST_LOG
          value: "info"
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_PTRACE
            - DAC_OVERRIDE
        volumeMounts:
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: tracefs
          mountPath: /sys/kernel/tracing
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
          type: DirectoryOrCreate
      - name: tracefs
        hostPath:
          path: /sys/kernel/tracing
          type: DirectoryOrCreate
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      nodeSelector:
        kubernetes.io/os: linux