apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kernel-observer-ebpf
  namespace: kernel-gossip
  labels:
    app: kernel-observer-ebpf
spec:
  selector:
    matchLabels:
      app: kernel-observer-ebpf
  template:
    metadata:
      labels:
        app: kernel-observer-ebpf
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: kernel-observer
        image: gcr.io/scaleops-dev-rel/kernel-observer-ebpf:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: WEBHOOK_URL
          value: "http://kernel-gossip-operator:8080/webhook/pixie"
        - name: RUST_LOG
          value: "kernel_observer=debug,aya=debug"
        - name: ENABLE_EBPF
          value: "true"
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: debugfs
          mountPath: /sys/kernel/debug
          readOnly: true
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: proc
        hostPath:
          path: /proc