apiVersion: v1
kind: Namespace
metadata:
  name: kernel-gossip
  labels:
    app.kubernetes.io/name: kernel-gossip
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kernel-gossip