apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
  namespace: kernel-gossip
  annotations:
    kernel-gossip.io/monitor: "true"
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "2", "--timeout", "3600s"]
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 100m
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-monitored
  namespace: kernel-gossip
  annotations:
    kernel-gossip.io/monitor: "true"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: 50m
      limits:
        cpu: 100m
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  namespace: kernel-gossip
  annotations:
    kernel-gossip.io/monitor: "true"
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do echo 'Working...'; sleep 5; done"]
    resources:
      requests:
        cpu: 50m
      limits:
        cpu: 100m