apiVersion: v1
kind: Pod
metadata:
  name: ebpf-test
  namespace: kernel-gossip
spec:
  containers:
  - name: ebpf-test
    image: gcr.io/google-containers/toolbox:latest
    command: ["/bin/sh"]
    args: ["-c", "uname -r && ls -la /sys/kernel/debug/tracing/ && cat /proc/sys/kernel/unprivileged_bpf_disabled && sleep 3600"]
    securityContext:
      privileged: true
      capabilities:
        add:
        - SYS_ADMIN
        - SYS_PTRACE
        - NET_ADMIN
        - PERFMON
        - BPF
    volumeMounts:
    - name: sys
      mountPath: /sys
      readOnly: false
    - name: debugfs
      mountPath: /sys/kernel/debug
      readOnly: false
  hostNetwork: true
  hostPID: true
  volumes:
  - name: sys
    hostPath:
      path: /sys
  - name: debugfs
    hostPath:
      path: /sys/kernel/debug