apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: kernel-gossip
  labels:
    app: test-nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
  restartPolicy: Always